# Generated by Django 5.1.5 on 2025-02-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_order_options_remove_cart_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.storecategory'),
        ),
    ]
