# Generated by Django 5.1.5 on 2025-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
