# Generated by Django 5.1.5 on 2025-02-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_close_at_store_discription_store_opens_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
