# Generated by Django 5.1.5 on 2025-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_categories/'),
        ),
    ]
