# Generated by Django 5.1.5 on 2025-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options_remove_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='Pending', max_length=12),
        ),
    ]
