# Generated by Django 5.1.5 on 2025-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_notes_alter_store_max_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
