# Generated by Django 5.1.5 on 2025-06-29 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_orderitem_notes_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_details',
            field=models.JSONField(blank=True, help_text='تفاصيل المقاس وقت الطلب', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, help_text='هل المنتج له مقاسات مختلفة؟'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='مثل: صغير، وسط، كبير', max_length=100)),
                ('size_type', models.CharField(choices=[('weight', 'وزن'), ('volume', 'حجم'), ('diameter', 'قطر'), ('length', 'طول'), ('other', 'أخرى')], default='other', max_length=20)),
                ('size_value', models.CharField(blank=True, help_text='مثل: 20 سم، 150 جم', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_after_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('product', 'size_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productsize'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.productsize'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_size')},
        ),
    ]
