# Generated by Django 5.1.5 on 2025-07-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_size_details_product_has_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['product', 'size_value', 'size_name']},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_size')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_after_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.productsize'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='store.productsize'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_type',
            field=models.CharField(choices=[('piece', 'عدد قطع / برجر'), ('diameter', 'قطر بيتزا (سم)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
