# Generated by Django 5.1.5 on 2025-07-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['product', 'size_name']},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size_value',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_type',
            field=models.CharField(choices=[('piece', 'عدد قطع / برجر'), ('diameter', 'قطر بيتزا (سم)'), ('default', 'افتراضي')], max_length=20),
        ),
    ]
